[programs.localnet]
incept = "7nDVRAFPTYDfcSZv9F7JxfbFxNDABfB1edG7gKHavwpt"
pyth = "CGN35EiXnmofHy3RmjcVYeQ4Yn5PyGaQuGV8TfEZnLs7"
jupiter_agg_mock = "B6jwZpUv7BC8Gzd5Ud5Y6FcjDFdfL4J7chmKXMig4mxY"
incept_comet_manager = "CNEvgsmVcYBwUzWQj6iss9MJaFDAzpF8BHSEjejLTXDh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"