[programs.localnet]
incept = "oA2F2E89xQnt5gox7wd6EhV3dJRFt57889UQyTq9che"
pyth = "FnHDAQniuRT3tjr71M9dwLvzVMtPRcHeZYgHaxXKjERR"
jupiter_agg_mock = "6Cfr7tR217PGkSgzDecqb6oeqaz5f32DD7xDzAvFq4Dm"
incept_comet_manager = "AB3CFBB2cY5godSjfZCJaTvq9qSKzqjzXmJWEwqQ7VJR"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"