[programs.localnet]
clone = "6xmjJPzcUQHb7Dhii4EfqvP8UxanxWYwRSpVY4yAUa2g"
pyth = "GegijnPoSC4ndamF6W3S57jLg8PTTBHbbttDMFvNqwyP"
jupiter_agg_mock = "4pVZGe5ygMM4CGhshdLUfSYjzDayxDkaVE5W6yWwC5Fi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/clone.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"