[programs.localnet]
incept = "2YSThxfPwJWYPAeBczUqbu2cyefjq9vAdDsPJU7PUVak"
pyth = "HJ37v65UZ97z6mbUrGXVZCqmQoYahDtK9i8ZNk2JLZut"
mock_usdc = "BtaD4H1JxGqrq9iZN7Z2if7cquTaMmCZ5Ra3JURjPGj5"
store = "6xGND4J7j36RyA5sYx8k5GTojF2U9awnXoiWrkYarD3c"
access_controller = "FvSzDSyxvu72HhTgAVnBkwVAwR9NvTqjR4tFBXia4bkv"
jupiter_agg_mock = "7BhcWQNaNiEBd9SW7xMGSJYDP7NQ9VRMLYaRZD1QjZh5"
incept_comet_manager = "HVsSygV6WvmPAqBFPBM8XYHhiYGhDFPMKmRixWdDpwtw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"