[programs.localnet]
incept = "GHwfUCuT3mtCrqVdsvAQ3VZy8dn6WiouijPfpQpQT61e"
pyth = "EERmAuBdXCAZitXKg1E2GaxFtwWDjZSctXKCvuWT19ki"
mock_usdc = "6uDBSgCWnP2nxk5vdNET8bYbn1Hav9UweMDUr5JDhCpu"
store = "Gv7JfdRSf7hAPafhGWkpGoZUwQdd5JhBrJEWFtYpatfy"
access_controller = "5zfL9db58B2Uutx12HzyeoPXei4Z2EbFSXb3vLCMjxJY"
jupiter_agg_mock = "97w9ahzStYbcNJZasNaGj6UQ6ruQou4n1nGozdQi6poJ"
incept_comet_manager = "6HAQXsz7ScT5SueXukgDB8ExE9FKeqj5q1z925SujZsu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"