[programs.localnet]
clone = "GCXnnWFmt4zFmoAo2nRGe4qQyuusLzDW7CVN484bHMvA"
pyth = "B527xTykF5Ab5ZDg49TgdJk7dszXvjne3gGrFH3qtLir"
jupiter_agg_mock = "G9fZ4yPY66oqrCGtCzrdbSyqBw8xFjSWAe5quV61cb75"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/clone.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"