[programs.localnet]
incept = "FbFjJC5XVPszxumC5jGVkDkV19TgJP7LWmsX21cRSXKL"
pyth = "7741WpkbdmZPGmqzPpsP3LdbzCwtMgxWH9tjdERnAzg8"
mock_usdc = "ED1yj7uXEZRFXwFU8QMtD2CCnpkLiTq46W1cNKFqo9qV"
store = "Haz47L8yvvthM99yy7hGi9jcPjVJSL1anMS238Ta6RFp"
access_controller = "FvSzDSyxvu72HhTgAVnBkwVAwR9NvTqjR4tFBXia4bkv"
jupiter_agg_mock = "CBM3RJyXMmu2cCSmBc1Vb5BB4Xy8hks3QQD4TcFYHoVg"
incept_comet_manager = "9UUKudw6whsFzWRxvyxQ1Ztet8cTqpHJJ5WpUfSbATYt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"