[programs.localnet]
incept = "65ifrH76MWRp4JqePYDQrCDDd5LFnxHwonXhMw55jcCx"
pyth = "GBSAG34H6o8SsAZsjpU77wTfvjFPTPueMf7s4uempT9u"
mock_usdc = "J4wFpMDiqxGPV4YkmaUYtCaPVRoSHcTN9EsaC1NsmfNi"
store = "Ef5PwEgoGcXV98XcebNKLMxNktCY911WYbD9CMjPTpxF"
access_controller = "DrnK2nD8HFqiooNuY7HdWQPRsRV6Q7aMtMWfYY28xKLv"
jupiter_agg_mock = "EVaviR93vZbBEQ4fXNLqShoaUPRR5tGsPpSbx6o5axjE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/incept.ts"
test_liquidation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/liquidation.ts"